### ISSUE TITLE
Fonts path is always wrong

### ISSUE THREAD

**Issue by jondcampbell** [mitydigital/statamic-google-fonts#1]
When I had the fonts set to inline it was trying to load the fonts over http and then I disabled the inline toggle and now it loads them like this: (hiding the domain name since site is still a WIP)

https://thedomain.com/storage/fonts/d50232f0c4/thedomain.com/storage/fonts/d50232f0c4/splayfairv20nkfc9d7po4khmuj5-ztz-wcmuxynak-5uqzxkoramxw6vnpe2iuocpqnjlmqhy.woff2

My storage folder is linked
I've tried php artisan google-fonts:fetch
I've tried clearing the artisan config cache, route cache, statamic cache.
I've run npm run production

So it just keeps giving me 404's when it tries to load the font.

I'm on Laravel Forge hosting on Digital Ocean
APP_URL="https://thedomain.com"

This font path exists and is the woff file.
https://thedomain.com/storage/fonts/d50232f0c4/slibrefranklinv14jizdrevithgc8qdibstkq4xkriuf2zczivbj.woff2

Any ideas of how I can get this to work?

My composer packages list in case that helps
```"require": {
        "php": "^8.1",
        "guzzlehttp/guzzle": "^7.2",
        "jacksleight/statamic-bard-mutator": "^2.3",
        "laravel/framework": "^10.16",
        "laravel/sanctum": "^3.2",
        "laravel/tinker": "^2.8",
        "mitydigital/statamic-google-fonts": "^1.0",
        "ndx/statamic-bard-color-picker": "^1.2",
        "plugrbase/statamic-maintenance-mode": "^1.07",
        "spatie/browsershot": "^4.0",
        "spatie/statamic-responsive-images": "^4.1",
        "statamic/cms": "^4.0",
        "studio1902/statamic-peak-browser-appearance": "^3.0",
        "studio1902/statamic-peak-commands": "^4.0",
        "studio1902/statamic-peak-seo": "^8.0",
        "studio1902/statamic-peak-tools": "^4.0"
    },
    "require-dev": {
        "barryvdh/laravel-debugbar": "^3.8.1",
        "fakerphp/faker": "^1.9.1",
        "laravel/pint": "^1.0",
        "laravel/sail": "^1.18",
        "mockery/mockery": "^1.4.4",
        "nunomaduro/collision": "^7.0",
        "phpunit/phpunit": "^10.1",
        "spatie/laravel-ignition": "^2.0"
    },```

**Comment by jondcampbell** [comment]
I deleted my fonts directory at /public/storage/fonts and then ran the `php artisan google-fonts:fetch` command and it seems like that created the fonts directory again but with different permissions and now the font urls are proper for my site.
I think yesterday I tried creating a fonts directory when I noticed there wasn't one in storage yet and that confused things.

**Comment by martyf** [comment]
So you have it all sorted? 

The creation of the `fonts` folder is actually from the root [package](https://github.com/spatie/laravel-google-fonts), not this package: this package adds Statamic support for the tag - but the underlying behaviour is not changed.

**Comment by jondcampbell** [comment]
@martyf Yes, seems to be working now. Wasn't sure how to close my issue.

**Comment by martyf** [comment]
No worries at all, will close off.
